<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\Hash;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {

        $users = [
            [
                'name' => 'Juan',
                'email' => 'juan.perez@example.com',
                'apellido' => 'Pérez',
                'fecha_nac' => '1990-05-12',
                'telefono' => '123456789',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'), 
                'remember_token' => Str::random(60),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Maria',
                'email' => 'maria.gonzalez@example.com',
                'apellido' => 'González',
                'fecha_nac' => '1985-11-25',
                'telefono' => '098765431',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'), 
                'remember_token' => Str::random(60),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Carlos',
                'email' => 'carlos.diaz@example.com',
                'apellido' => 'Díaz',
                'fecha_nac' => '1992-07-19',
                'telefono' => '112233445',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'), 
                'remember_token' => Str::random(60),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Joel',
                'email' => 'joel.zeballos@example.com',
                'apellido' => 'Zeballos',
                'fecha_nac' => '2000-05-20',
                'telefono' => '986352147',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'), 
                'remember_token' => Str::random(60),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Henry',
                'email' => 'henry.mamani@example.com',
                'apellido' => 'Mamani',
                'fecha_nac' => '1999-08-31',
                'telefono' => '365278952',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'), 
                'remember_token' => Str::random(60),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Kyle',
                'email' => 'longeugene@harris-stevens.org',
                'apellido' => 'Rivera',
                'fecha_nac' => '1985-10-09',
                'telefono' => '478596123',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'), 
                'remember_token' => Str::random(60),
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'name' => 'Melinda',
                'email' => 'jeffreyhenderson@moreno.com',
                'apellido' => 'Smith',
                'fecha_nac' => '1965-09-22',
                'telefono' => '947-760-5876',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'), 
                'remember_token' => Str::random(60),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Donna',
                'email' => 'stevenramos@gmail.com',
                'apellido' => 'White',
                'fecha_nac' => '1956-09-16',
                'telefono' => '031.122.9498',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'), 
                'remember_token' => Str::random(60),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Oscar',
                'email' => 'bwang@payne-mays.net',
                'apellido' => 'Chase',
                'fecha_nac' => '1994-09-20',
                'telefono' => '368-771-5302x916',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'), 
                'remember_token' => Str::random(60),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'April',
                'email' => 'thompsonbrett@hotmail.com',
                'apellido' => 'Shaw',
                'fecha_nac' => '1974-12-14',
                'telefono' => '385.006.0191',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'), 
                'remember_token' => Str::random(60),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Lisa',
                'email' => 'yherman@dawson.org',
                'apellido' => 'Williams',
                'fecha_nac' => '1986-12-03',
                'telefono' => '095-858-2446x8076',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'), 
                'remember_token' => Str::random(60),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Brandy',
                'email' => 'npittman@bradley.info',
                'apellido' => 'Lee',
                'fecha_nac' => '1974-01-27',
                'telefono' => '(741)334-2822x3198',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'), 
                'remember_token' => Str::random(60),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Brian',
                'email' => 'brucedennis@hotmail.com',
                'apellido' => 'Kaiser',
                'fecha_nac' => '1995-04-19',
                'telefono' => '+1-945-380-0995x901',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'), 
                'remember_token' => Str::random(60),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Holly',
                'email' => 'donald95@anderson-palmer.info',
                'apellido' => 'Dalton',
                'fecha_nac' => '1964-09-18',
                'telefono' => '001-047-647-3132x0148',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'), 
                'remember_token' => Str::random(60),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Blake',
                'email' => 'garzachristopher@gmail.com',
                'apellido' => 'Bryant',
                'fecha_nac' => '2005-12-21',
                'telefono' => '233.200.5255',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'), 
                'remember_token' => Str::random(60),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Christina',
                'email' => 'derrick37@gmail.com',
                'apellido' => 'Potter',
                'fecha_nac' => '1962-11-03',
                'telefono' => '(421)585-7250x75884',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'), 
                'remember_token' => Str::random(60),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Sheri',
                'email' => 'druiz@hotmail.com',
                'apellido' => 'Rojas',
                'fecha_nac' => '1988-07-21',
                'telefono' => '6698387976',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'), 
                'remember_token' => Str::random(60),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Michael',
                'email' => 'jonathanbrown@green.com',
                'apellido' => 'Hoffman',
                'fecha_nac' => '1978-05-21',
                'telefono' => '(057)649-2962x5560',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'), 
                'remember_token' => Str::random(60),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Michelle',
                'email' => 'liubrett@gmail.com',
                'apellido' => 'Hoffman',
                'fecha_nac' => '1959-09-07',
                'telefono' => '617-887-3564',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'), 
                'remember_token' => Str::random(60),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Melanie',
                'email' => 'brianlloyd@young-smith.biz',
                'apellido' => 'Sullivan',
                'fecha_nac' => '1981-03-01',
                'telefono' => '(932)501-8295x074',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'), 
                'remember_token' => Str::random(60),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Melissa',
                'email' => 'zavalajoan@henderson.com',
                'apellido' => 'Perez',
                'fecha_nac' => '1967-06-28',
                'telefono' => '(383)947-8958',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'), 
                'remember_token' => Str::random(60),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Richard',
                'email' => 'laurenkelley@reid.com',
                'apellido' => 'Lee',
                'fecha_nac' => '1971-02-09',
                'telefono' => '125-646-9846x625',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'), 
                'remember_token' => Str::random(60),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'James',
                'email' => 'julie55@hotmail.com',
                'apellido' => 'Acosta',
                'fecha_nac' => '1984-11-12',
                'telefono' => '(956)215-2851',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'), 
                'remember_token' => Str::random(60),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Jessica',
                'email' => 'zthomas@miller.com',
                'apellido' => 'Holt',
                'fecha_nac' => '1952-02-04',
                'telefono' => '4731146516',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'), 
                'remember_token' => Str::random(60),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'James',
                'email' => 'evantorres@gmail.com',
                'apellido' => 'Olson',
                'fecha_nac' => '1994-07-11',
                'telefono' => '861.368.7169',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'), 
                'remember_token' => Str::random(60),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Andrew',
                'email' => 'daniel74@bauer-green.com',
                'apellido' => 'Craig',
                'fecha_nac' => '2003-07-16',
                'telefono' => '+1-933-156-9542x3967',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'), 
                'remember_token' => Str::random(60),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Theodore',
                'email' => 'bonniegutierrez@walton-garner.net',
                'apellido' => 'Jacobs',
                'fecha_nac' => '1947-09-25',
                'telefono' => '711.547.6958x13521',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'), 
                'remember_token' => Str::random(60),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Kevin',
                'email' => 'seaton@wilcox.com',
                'apellido' => 'Johnson',
                'fecha_nac' => '1977-03-13',
                'telefono' => '534.132.7600',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'), 
                'remember_token' => Str::random(60),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Frederick',
                'email' => 'msanchez@hotmail.com',
                'apellido' => 'Bailey',
                'fecha_nac' => '1975-12-10',
                'telefono' => '+1-563-592-7664x089',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'), 
                'remember_token' => Str::random(60),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Shelley',
                'email' => 'barbermario@henderson.com',
                'apellido' => 'Wright',
                'fecha_nac' => '1996-07-24',
                'telefono' => '698-580-6818',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'), 
                'remember_token' => Str::random(60),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Tracy',
                'email' => 'prush@gmail.com',
                'apellido' => 'Sullivan',
                'fecha_nac' => '1953-09-06',
                'telefono' => '211.324.0441x8731',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'), 
                'remember_token' => Str::random(60),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Stephanie',
                'email' => 'heather45@gmail.com',
                'apellido' => 'Potter',
                'fecha_nac' => '1950-02-02',
                'telefono' => '310-906-7384x2018',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'), 
                'remember_token' => Str::random(60),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Debra',
                'email' => 'tyler60@myers-armstrong.com',
                'apellido' => 'Jackson',
                'fecha_nac' => '1953-11-08',
                'telefono' => '079.415.7021',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'), 
                'remember_token' => Str::random(60),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Michael',
                'email' => 'johnsonlaura@turner.org',
                'apellido' => 'Miller',
                'fecha_nac' => '1990-07-17',
                'telefono' => '749-448-6549x2897',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'), 
                'remember_token' => Str::random(60),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'David',
                'email' => 'roymartinez@yahoo.com',
                'apellido' => 'Chambers',
                'fecha_nac' => '1990-07-18',
                'telefono' => '(064)697-7787',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'), 
                'remember_token' => Str::random(60),
                'created_at' => now(),
                'updated_at' => now(),
            ]
        ];
        DB::table('users')->insert($users);
    }
}
