<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\Hash;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $users = [
            [
                'name' => 'Juan',
                'email' => 'juan.perez@example.com',
                'apellido' => 'Pérez',
                'fecha_nac' => '1990-05-12',
                'telefono' => '123456789',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'), 
                'remember_token' => Str::random(60),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Maria',
                'email' => 'maria.gonzalez@example.com',
                'apellido' => 'González',
                'fecha_nac' => '1985-11-25',
                'telefono' => '098765432',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'), 
                'remember_token' => Str::random(60),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Carlos',
                'email' => 'carlos.diaz@example.com',
                'apellido' => 'Díaz',
                'fecha_nac' => '1992-07-19',
                'telefono' => '112233445',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'), 
                'remember_token' => Str::random(60),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Joel',
                'email' => 'joel.zeballos@example.com',
                'apellido' => 'Zeballos',
                'fecha_nac' => '2000-05-20',
                'telefono' => '986352147',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'), 
                'remember_token' => Str::random(60),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Henry',
                'email' => 'henry.mamani@example.com',
                'apellido' => 'Mamani',
                'fecha_nac' => '1999-08-31',
                'telefono' => '365278695',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'), 
                'remember_token' => Str::random(60),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Joel',
                'email' => 'joel.huamani@example.com',
                'apellido' => 'Huamani',
                'fecha_nac' => '1990-05-12',
                'telefono' => '123456789',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'), 
                'remember_token' => Str::random(60),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Diego',
                'email' => 'diego.colca@example.com',
                'apellido' => 'Colca',
                'fecha_nac' => '1985-11-25',
                'telefono' => '087654321',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'), 
                'remember_token' => Str::random(60),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Kevin',
                'email' => 'kevin.roy@example.com',
                'apellido' => 'Roy',
                'fecha_nac' => '1992-07-19',
                'telefono' => '192233455',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'), 
                'remember_token' => Str::random(60),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Fabio',
                'email' => 'fabio.lora@example.com',
                'apellido' => 'Lora',
                'fecha_nac' => '2000-05-20',
                'telefono' => '986352787',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'), 
                'remember_token' => Str::random(60),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Gael',
                'email' => 'gael.mamani@example.com',
                'apellido' => 'Mamani',
                'fecha_nac' => '1999-08-31',
                'telefono' => '365278952',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'), 
                'remember_token' => Str::random(60),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Horacio',
                'email' => 'horacio.flores@example.com',
                'apellido' => 'Flores',
                'fecha_nac' => '1990-05-12',
                'telefono' => '485963217',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'),
                'remember_token' => Str::random(60),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Norma',
                'email' => 'norma.gonzalez@example.com',
                'apellido' => 'González',
                'fecha_nac' => '1985-11-25',
                'telefono' => '987654321',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'),
                'remember_token' => Str::random(60),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Pedro',
                'email' => 'pedro.lopez@example.com',
                'apellido' => 'López',
                'fecha_nac' => '1992-03-08',
                'telefono' => '876543210',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'),
                'remember_token' => Str::random(60),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Ana',
                'email' => 'ana.martinez@example.com',
                'apellido' => 'Martínez',
                'fecha_nac' => '1998-09-15',
                'telefono' => '765432109',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'),
                'remember_token' => Str::random(60),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Luis',
                'email' => 'luis.ramirez@example.com',
                'apellido' => 'Ramírez',
                'fecha_nac' => '1987-02-14',
                'telefono' => '654321098',
                'email_verified_at' => now(),
                'password' => Hash::make('password123'),
                'remember_token' => Str::random(60),
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];
        DB::table('users')->insert($users);
    }
}
